(function() {

  window.nfforg.data_acted_management = {};

  var data = window.nfforg.data_acted_management;

data.acted_collab_admin = 
[{"data": {"node": {"count": 18859, "total_count": 19845, "label": "Number of Responses", "perc": 0.9503149407911312}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_collab_admin", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_collab_admin", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 1315, "perc": 0.06972798133517154, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 156, "perc": 0.11863117870722434, "question_key": "acted_collab_admin", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 1159, "perc": 0.8813688212927757, "question_key": "acted_collab_admin", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 1935, "perc": 0.10260353147038549, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 267, "perc": 0.13798449612403102, "question_key": "acted_collab_admin", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 1668, "perc": 0.862015503875969, "question_key": "acted_collab_admin", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 4607, "perc": 0.244286547536985, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 804, "perc": 0.17451703928803994, "question_key": "acted_collab_admin", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 3803, "perc": 0.82548296071196, "question_key": "acted_collab_admin", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5983, "perc": 0.3172490588048147, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 956, "perc": 0.1597860605047635, "question_key": "acted_collab_admin", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 5027, "perc": 0.8402139394952365, "question_key": "acted_collab_admin", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 0.2661328808526433, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 1282, "perc": 0.2554293684000797, "question_key": "acted_collab_admin", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 3737, "perc": 0.7445706315999203, "question_key": "acted_collab_admin", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_collab_admin"}];
    window.nfforg.decrementYearDisplayAndAppend(data.acted_collab_admin, 732, 0.13);


data.acted_merge = 
[{"data": {"node": {"count": 18859, "total_count": 19845, "label": "Number of Responses", "perc": 0.9503149407911312}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_merge", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_merge", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 1315, "perc": 0.06972798133517154, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 19, "perc": 0.014448669201520912, "question_key": "acted_merge", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 1296, "perc": 0.9855513307984791, "question_key": "acted_merge", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 1935, "perc": 0.10260353147038549, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 31, "perc": 0.016020671834625324, "question_key": "acted_merge", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 1904, "perc": 0.9839793281653747, "question_key": "acted_merge", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 4607, "perc": 0.244286547536985, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 107, "perc": 0.02322552637291079, "question_key": "acted_merge", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4500, "perc": 0.9767744736270892, "question_key": "acted_merge", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5983, "perc": 0.3172490588048147, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 119, "perc": 0.01988968744776868, "question_key": "acted_merge", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 5864, "perc": 0.9801103125522314, "question_key": "acted_merge", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 0.2661328808526433, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 138, "perc": 0.02749551703526599, "question_key": "acted_merge", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4881, "perc": 0.972504482964734, "question_key": "acted_merge", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_merge"}];
    window.nfforg.decrementYearDisplayAndAppend(data.acted_merge, 112, 0.02);


//data.acted_change_fundraising = 
//[{"data": {"node": {"count": 11002, "total_count": 19845, "label": "Number of Responses", "perc": 0.5543965734441925}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_change_fundraising", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_change_fundraising", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_change_fundraising", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_change_fundraising", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_change_fundraising", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_change_fundraising", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_change_fundraising", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_change_fundraising", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5983, "perc": 0.5438102163243047, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 1465, "perc": 0.2448604379074043, "question_key": "acted_change_fundraising", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4518, "perc": 0.7551395620925957, "question_key": "acted_change_fundraising", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 0.45618978367569535, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 1155, "perc": 0.2301255230125523, "question_key": "acted_change_fundraising", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 3864, "perc": 0.7698744769874477, "question_key": "acted_change_fundraising", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_change_fundraising"}];

/*
data.acted_earned_revenue = 
[{"data": {"node": {"count": 5019, "total_count": 19845, "label": "Number of Responses", "perc": 0.2529100529100529}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_earned_revenue", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_earned_revenue", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_earned_revenue", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_earned_revenue", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_earned_revenue", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_earned_revenue", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_earned_revenue", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_earned_revenue", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_earned_revenue", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_earned_revenue", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 1.0, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 921, "perc": 0.1835026897788404, "question_key": "acted_earned_revenue", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4098, "perc": 0.8164973102211596, "question_key": "acted_earned_revenue", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_earned_revenue"}];
  window.nfforg.decrementYearDisplayAndAppend(data.acted_earned_revenue, 
*/

// data.acted_advocacy = 
// [{"data": {"node": {"count": 11002, "total_count": 19845, "label": "Number of Responses", "perc": 0.5543965734441925}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_advocacy", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_advocacy", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_advocacy", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_advocacy", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_advocacy", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_advocacy", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_advocacy", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_advocacy", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5983, "perc": 0.5438102163243047, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 2544, "perc": 0.42520474678255055, "question_key": "acted_advocacy", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 3439, "perc": 0.5747952532174494, "question_key": "acted_advocacy", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 0.45618978367569535, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 2164, "perc": 0.43116158597330145, "question_key": "acted_advocacy", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 2855, "perc": 0.5688384140266985, "question_key": "acted_advocacy", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_advocacy"}];

//data.acted_alt_funds = 
//[{"data": {"node": {"count": 11002, "total_count": 19845, "label": "Number of Responses", "perc": 0.5543965734441925}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_alt_funds", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_alt_funds", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_alt_funds", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_alt_funds", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_alt_funds", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_alt_funds", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_alt_funds", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_alt_funds", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5983, "perc": 0.5438102163243047, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 1125, "perc": 0.1880327594852081, "question_key": "acted_alt_funds", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4858, "perc": 0.811967240514792, "question_key": "acted_alt_funds", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 0.45618978367569535, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 965, "perc": 0.19226937636979477, "question_key": "acted_alt_funds", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4054, "perc": 0.8077306236302052, "question_key": "acted_alt_funds", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_alt_funds"}];

data.acted_add_reserve = 
[{"data": {"node": {"count": 17544, "total_count": 19845, "label": "Number of Responses", "perc": 0.8840513983371127}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_add_reserve", "label": "Yes", "key": "yes", "order": "3"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_add_reserve", "label": "No", "key": "no", "order": "3"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_add_reserve", "label": "Yes", "key": "yes", "order": "3"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_add_reserve", "label": "No", "key": "no", "order": "3"}}]}, {"node": {"count": 1935, "perc": 0.11029411764705882, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 492, "perc": 0.25426356589147286, "question_key": "acted_add_reserve", "label": "Yes", "key": "yes", "order": "3"}}, {"node": {"count": 1443, "perc": 0.7457364341085271, "question_key": "acted_add_reserve", "label": "No", "key": "no", "order": "3"}}]}, {"node": {"count": 4607, "perc": 0.2625968992248062, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 1079, "perc": 0.23420881267636207, "question_key": "acted_add_reserve", "label": "Yes", "key": "yes", "order": "3"}}, {"node": {"count": 3528, "perc": 0.7657911873236379, "question_key": "acted_add_reserve", "label": "No", "key": "no", "order": "3"}}]}, {"node": {"count": 5983, "perc": 0.34102827177382583, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 1215, "perc": 0.20307538024402474, "question_key": "acted_add_reserve", "label": "Yes", "key": "yes", "order": "3"}}, {"node": {"count": 4768, "perc": 0.7969246197559753, "question_key": "acted_add_reserve", "label": "No", "key": "no", "order": "3"}}]}, {"node": {"count": 5019, "perc": 0.2860807113543092, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 1228, "perc": 0.24467025303845388, "question_key": "acted_add_reserve", "label": "Yes", "key": "yes", "order": "3"}}, {"node": {"count": 3791, "perc": 0.7553297469615461, "question_key": "acted_add_reserve", "label": "No", "key": "no", "order": "3"}}]}]}, "id": "year/acted_add_reserve"}];
    window.nfforg.decrementYearDisplayAndAppend(data.acted_add_reserve, 1137, 0.21);


data.acted_use_reserve = 
[{"data": {"node": {"count": 18859, "total_count": 19845, "label": "Number of Responses", "perc": 0.9503149407911312}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_use_reserve", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_use_reserve", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 1315, "perc": 0.06972798133517154, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 447, "perc": 0.33992395437262357, "question_key": "acted_use_reserve", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 868, "perc": 0.6600760456273764, "question_key": "acted_use_reserve", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 1935, "perc": 0.10260353147038549, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 652, "perc": 0.33695090439276487, "question_key": "acted_use_reserve", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 1283, "perc": 0.6630490956072351, "question_key": "acted_use_reserve", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 4607, "perc": 0.244286547536985, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 1238, "perc": 0.2687215107445192, "question_key": "acted_use_reserve", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 3369, "perc": 0.7312784892554808, "question_key": "acted_use_reserve", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5983, "perc": 0.3172490588048147, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 1163, "perc": 0.19438408825004178, "question_key": "acted_use_reserve", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4820, "perc": 0.8056159117499582, "question_key": "acted_use_reserve", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 0.2661328808526433, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 1006, "perc": 0.20043833432954772, "question_key": "acted_use_reserve", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4013, "perc": 0.7995616656704523, "question_key": "acted_use_reserve", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_use_reserve"}];
    window.nfforg.decrementYearDisplayAndAppend(data.acted_use_reserve, 870, 0.16);


/*
data.acted_capital_camp = 
[{"data": {"node": {"count": 5019, "total_count": 19845, "label": "Number of Responses", "perc": 0.2529100529100529}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_capital_camp", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_capital_camp", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_capital_camp", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_capital_camp", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_capital_camp", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_capital_camp", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_capital_camp", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_capital_camp", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_capital_camp", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_capital_camp", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 1.0, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 465, "perc": 0.09264793783622235, "question_key": "acted_capital_camp", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4554, "perc": 0.9073520621637776, "question_key": "acted_capital_camp", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_capital_camp"}];
  window.nfforg.decrementYearDisplayAndAppend(data.acted_capital_camp, 


data.acted_org_restructure = 
[{"data": {"node": {"count": 5019, "total_count": 19845, "label": "Number of Responses", "perc": 0.2529100529100529}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_org_restructure", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_org_restructure", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_org_restructure", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_org_restructure", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_org_restructure", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_org_restructure", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_org_restructure", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_org_restructure", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_org_restructure", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_org_restructure", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 1.0, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 954, "perc": 0.19007770472205618, "question_key": "acted_org_restructure", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4065, "perc": 0.8099222952779438, "question_key": "acted_org_restructure", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_org_restructure"}];
  window.nfforg.decrementYearDisplayAndAppend(data.acted_org_restructure, 
*/


/*
data.acted_strat_plan = 
[{"data": {"node": {"count": 5019, "total_count": 19845, "label": "Number of Responses", "perc": 0.2529100529100529}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_strat_plan", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_strat_plan", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_strat_plan", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_strat_plan", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_strat_plan", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_strat_plan", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_strat_plan", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_strat_plan", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_strat_plan", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_strat_plan", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 1.0, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 1951, "perc": 0.3887228531579996, "question_key": "acted_strat_plan", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 3068, "perc": 0.6112771468420004, "question_key": "acted_strat_plan", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_strat_plan"}];
  window.nfforg.decrementYearDisplayAndAppend(data.acted_strat_plan, 


data.acted_fin_consultants = 
[{"data": {"node": {"count": 5019, "total_count": 19845, "label": "Number of Responses", "perc": 0.2529100529100529}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_fin_consultants", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_fin_consultants", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_fin_consultants", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_fin_consultants", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_fin_consultants", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_fin_consultants", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_fin_consultants", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_fin_consultants", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_fin_consultants", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_fin_consultants", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 1.0, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 1129, "perc": 0.22494520820880654, "question_key": "acted_fin_consultants", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 3890, "perc": 0.7750547917911935, "question_key": "acted_fin_consultants", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_fin_consultants"}];
  window.nfforg.decrementYearDisplayAndAppend(data.acted_fin_consultants, 


data.acted_tech_upgrade = 
[{"data": {"node": {"count": 5019, "total_count": 19845, "label": "Number of Responses", "perc": 0.2529100529100529}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_tech_upgrade", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_tech_upgrade", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_tech_upgrade", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_tech_upgrade", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_tech_upgrade", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_tech_upgrade", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_tech_upgrade", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_tech_upgrade", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_tech_upgrade", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_tech_upgrade", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 1.0, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 2013, "perc": 0.40107591153616257, "question_key": "acted_tech_upgrade", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 3006, "perc": 0.5989240884638374, "question_key": "acted_tech_upgrade", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_tech_upgrade"}];
  window.nfforg.decrementYearDisplayAndAppend(data.acted_tech_upgrade, 


data.acted_borrow_board = 
[{"data": {"node": {"count": 5019, "total_count": 19845, "label": "Number of Responses", "perc": 0.2529100529100529}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_borrow_board", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_borrow_board", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_borrow_board", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_borrow_board", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_borrow_board", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_borrow_board", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_borrow_board", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_borrow_board", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_borrow_board", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_borrow_board", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 1.0, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 155, "perc": 0.03088264594540745, "question_key": "acted_borrow_board", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4864, "perc": 0.9691173540545925, "question_key": "acted_borrow_board", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_borrow_board"}];
  window.nfforg.decrementYearDisplayAndAppend(data.acted_borrow_board, 


// data.acted_delay_vendors = 
// [{"data": {"node": {"count": 8269, "total_count": 19845, "label": "Number of Responses", "perc": 0.4166792642983119}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_delay_vendors", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_delay_vendors", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 1315, "perc": 0.15902769379610593, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 303, "perc": 0.23041825095057034, "question_key": "acted_delay_vendors", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 1012, "perc": 0.7695817490494297, "question_key": "acted_delay_vendors", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 1935, "perc": 0.23400653041480227, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 379, "perc": 0.1958656330749354, "question_key": "acted_delay_vendors", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 1556, "perc": 0.8041343669250646, "question_key": "acted_delay_vendors", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_delay_vendors", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_delay_vendors", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_delay_vendors", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_delay_vendors", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 0.6069657757890918, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 413, "perc": 0.08228730822873083, "question_key": "acted_delay_vendors", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4606, "perc": 0.9177126917712691, "question_key": "acted_delay_vendors", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_delay_vendors"}];

data.acted_buy_facility = 
[{"data": {"node": {"count": 5019, "total_count": 19845, "label": "Number of Responses", "perc": 0.2529100529100529}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_buy_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_buy_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_buy_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_buy_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_buy_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_buy_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_buy_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_buy_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_buy_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_buy_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 1.0, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 574, "perc": 0.11436541143654114, "question_key": "acted_buy_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4445, "perc": 0.8856345885634589, "question_key": "acted_buy_facility", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_buy_facility"}];
  window.nfforg.decrementYearDisplayAndAppend(data.acted_buy_facility, 


data.acted_lease_facility = 
[{"data": {"node": {"count": 5019, "total_count": 19845, "label": "Number of Responses", "perc": 0.2529100529100529}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_lease_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_lease_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_lease_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_lease_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_lease_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_lease_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_lease_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_lease_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_lease_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_lease_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 1.0, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 550, "perc": 0.10958358238692967, "question_key": "acted_lease_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4469, "perc": 0.8904164176130703, "question_key": "acted_lease_facility", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_lease_facility"}];
  window.nfforg.decrementYearDisplayAndAppend(data.acted_lease_facility, 


data.acted_sell_facility = 
[{"data": {"node": {"count": 5019, "total_count": 19845, "label": "Number of Responses", "perc": 0.2529100529100529}, "children": [{"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2009", "key": "2009", "order": "1"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_sell_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_sell_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2010", "key": "2010", "order": "2"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_sell_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_sell_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2011", "key": "2011", "order": "3"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_sell_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_sell_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2012", "key": "2012", "order": "4"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_sell_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_sell_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 0, "perc": 0.0, "question_key": "year", "label": "2013", "key": "2013", "order": "5"}, "children": [{"node": {"count": 0, "perc": 0, "question_key": "acted_sell_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 0, "perc": 0, "question_key": "acted_sell_facility", "label": "No", "key": "no", "order": "2"}}]}, {"node": {"count": 5019, "perc": 1.0, "question_key": "year", "label": "2014", "key": "2014", "order": "6"}, "children": [{"node": {"count": 100, "perc": 0.019924287706714484, "question_key": "acted_sell_facility", "label": "Yes", "key": "yes", "order": "1"}}, {"node": {"count": 4919, "perc": 0.9800757122932855, "question_key": "acted_sell_facility", "label": "No", "key": "no", "order": "2"}}]}]}, "id": "year/acted_sell_facility"}];
  window.nfforg.decrementYearDisplayAndAppend(data.acted_sell_facility, 
*/

})();
